# Generated by Django 4.1.4 on 2022-12-17 15:20

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('_id', models.CharField(db_column='id', default=uuid.uuid4, max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('secrets_key', models.CharField(max_length=255, unique=True)),
                ('ctime', models.DateTimeField(default=datetime.datetime.now, verbose_name='注册时间')),
                ('utime', models.DateTimeField(default=datetime.datetime.now, verbose_name='最后一次更新时间')),
                ('reg_reason', models.CharField(default='自动发现后并注册。', max_length=1024, verbose_name='注册方式')),
                ('oper_id', models.CharField(max_length=40, verbose_name='操作人ID')),
                ('remarks', models.TextField(default='一般操作。', verbose_name='备注')),
            ],
            options={
                'verbose_name': '代理工具',
                'verbose_name_plural': '代理工具',
                'db_table': 't_agent',
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(default='--', max_length=40, verbose_name="代理工具ID(但该项为模板时，值为'--') ")),
                ('path', models.TextField(verbose_name='配置文件路径')),
                ('section', models.CharField(max_length=255, verbose_name='配置段')),
                ('key', models.CharField(max_length=255, verbose_name='配置项')),
                ('value', models.CharField(max_length=1024, verbose_name='配置值')),
                ('ctime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('utime', models.DateTimeField(default=datetime.datetime.now, verbose_name='最后一次更新时间')),
                ('oper_id', models.CharField(max_length=40, verbose_name='操作人ID')),
                ('remarks', models.TextField(default='一般操作。', verbose_name='备注')),
                ('is_template', models.BooleanField(default=False, verbose_name='是否为模板字段')),
            ],
            options={
                'verbose_name': '配置',
                'verbose_name_plural': '配置',
                'db_table': 't_config',
            },
        ),
        migrations.CreateModel(
            name='ConfigTemplate',
            fields=[
                ('_id', models.CharField(db_column='id', default=uuid.uuid4, max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='名称')),
                ('owner_id', models.UUIDField(verbose_name='拥有者ID')),
                ('path', models.TextField(verbose_name='配置文件路径')),
                ('salt', models.CharField(max_length=1024, verbose_name='Salt(AES加密, 最大长度=1024')),
                ('ctime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('utime', models.DateTimeField(default=datetime.datetime.now, verbose_name='最后一次更新时间')),
            ],
            options={
                'verbose_name': '配置模板',
                'verbose_name_plural': '配置模板',
                'db_table': 't_config_template',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('_id', models.CharField(db_column='id', default=uuid.uuid4, max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='名称')),
                ('synopisis', models.TextField(blank=True, verbose_name='简介')),
                ('ctime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('utime', models.DateTimeField(default=datetime.datetime.now, verbose_name='最后一次更新时间')),
            ],
            options={
                'verbose_name': '用户组',
                'verbose_name_plural': '用户组',
                'db_table': 't_group',
            },
        ),
        migrations.CreateModel(
            name='LogItem',
            fields=[
                ('_id', models.CharField(db_column='id', default=uuid.uuid4, max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024, verbose_name='操作内容')),
                ('oper_id', models.CharField(max_length=40, verbose_name='操作人ID')),
                ('ctime', models.DateTimeField(default=datetime.datetime.now, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 't_log_item',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('_id', models.CharField(db_column='id', default=uuid.uuid4, max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='姓名')),
                ('no', models.CharField(max_length=128, verbose_name='工号')),
                ('domain', models.CharField(max_length=1024, verbose_name='组织架构路径')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码(AES对称加密)')),
                ('email', models.EmailField(max_length=1024, verbose_name='工作邮箱')),
                ('email_backup', models.EmailField(max_length=1024, verbose_name='备用邮箱')),
                ('phone', models.CharField(max_length=255, verbose_name='工作手机')),
                ('ctime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('utime', models.DateTimeField(default=datetime.datetime.now, verbose_name='最后一次更新时间')),
            ],
            options={
                'verbose_name': '操作者',
                'verbose_name_plural': '操作者',
                'db_table': 't_operator',
            },
        ),
        migrations.CreateModel(
            name='OperatorGroupRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_column='uid', max_length=255, verbose_name='UID')),
                ('gid', models.CharField(db_column='gid', max_length=255, verbose_name='GID')),
            ],
            options={
                'verbose_name': '用户组关系',
                'verbose_name_plural': '用户组关系',
                'db_table': 't_operator_group_ref',
            },
        ),
        migrations.CreateModel(
            name='ServiceConfig',
            fields=[
                ('_id', models.CharField(db_column='id', default=uuid.uuid4, max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_use', models.BooleanField(default=False, verbose_name='是否启用')),
                ('cname', models.CharField(blank=True, max_length=255, verbose_name='别名')),
                ('ctime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('utime', models.DateTimeField(default=datetime.datetime.now, verbose_name='最后一次更新时间')),
            ],
            options={
                'verbose_name': 'Systemd Online 服务配置(危险) ',
                'verbose_name_plural': 'Systemd Online 服务配置(危险) ',
                'db_table': 't_service_config',
            },
        ),
    ]
