# Generated by Django 4.1.4 on 2022-12-17 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='synopisis',
            new_name='synopsis',
        ),
    ]
